### PR TITLE
Use async-executor instead of smol

### PR DESCRIPTION
**Pull request by notgull**
### Checklist

* [x] I have read the [Contributor Guide](../../CONTRIBUTING.md)
* [x] I have read and agree to the [Code of Conduct](../../CODE_OF_CONDUCT.md)
* [x] I have added a description of my changes and why I'd like them included in the section below

### Description of Changes

Replaces `smol` with the `async-executor` crate, so that this crate doesn't import all of `smol` just for the executor.

### Related Issues

N/A

### CODE REVIEW

**Review by melody-rs — COMMENTED** [review]
It might be a good idea to rename the smol feature to async-executor

**Comment by notgull** [comment]
> It might be a good idea to rename the smol feature to async-executor

Maybe; that being said I didn't want to make a breaking change unless it's fine.

**Review by emilk — APPROVED** [review]

**Comment by notgull** [comment]
`cargo deny` failure is due to `syn` duplication in the `value-bag` crate.

**Comment by melody-rs** [comment]
> Maybe; that being said I didn't want to make a breaking change unless it's fine.

The smol feature actually isn't pushed to crates.io yet, so it should be fine?

As far as I am aware, only Luminol (which is *my* project and the reason I added the feature in the first place) uses the feature too?

**Comment by notgull** [comment]
> The smol feature actually isn't pushed to crates.io yet, so it should be fine?

If it hasn't been published, then we should be fine! Changed it.

**Pull request closed without merging**
